/**
 * 평가 가중치 (센티폰 단위, 폰 = 100 고정).
 * 부호가 있는 값이다: 음수는 감점 항목.
 * tools/tune.ts(Texel 튜닝)의 --apply가 이 파일을 다시 쓴다.
 * 마지막 튜닝: reports/tune-20260916-092628.md
 */
export const WEIGHTS: Readonly<Record<string, number>> = {
  'piece.p': 100,
  'piece.n': 344,
  'piece.b': 344,
  'piece.r': 558,
  'piece.q': 1179,
  promotedKing: 355,
  'enhanced.p': 319,
  'enhanced.n': 494,
  'enhanced.b': 117,
  'enhanced.r': 88,
  pawnAdvance: 20,
  pawnCenter: 17,
  knightCenter: 42,
  bishopCenter: 32,
  queenCenter: 20,
  royalKingCenter: 3,
  rookOpenFile: 83,
  passedPawn: -56,
  passedPawnAdvance: 39,
  doubledPawn: -45,
  bishopPair: 52,
  extraRoyal: 893,
  empressActive: 286,
  inCheck: -51,
  cooldown: -35,
  cooldownLeft: -3,
  resourceFull: 4,
  resourceUsable: -10,
  'resource.telekinesis.1': 74,
  'resource.telekinesis.2': 68,
  'resource.telekinesis.3': 65,
  'resource.haste.1': 196,
  'resource.haste.2': 191,
  'resource.haste.3': 190,
  'resource.teleport.1': 134,
  'resource.teleport.2': 122,
  'resource.revive.1': 45,
  'resource.revive.2': 47,
  'resource.revive.3': 48,
  'resource.revive.4': 48,
  'resource.revive.5': 47,
  'resource.revive.6': 47,
  'resource.revive.7': 46,
  'resource.rewind.1': 41,
  'resource.rewind.2': 41,
  'resource.rewind.3': 45,
  'resource.heavyInfantry.1': 96,
  'resource.lancer.1': -7,
  'resource.lancer.2': -11,
  'resource.chariot.1': -8,
  'resource.chariot.2': -10,
  'resource.paladin.1': -23,
  'resource.paladin.2': -21,
  'resource.empress.1': -11,
  'resource.empress.2': -8,
  'resource.heir.1': -105,
  'resource.heir.2': -100,
  'resource.heir.3': -91,
  'resource.heir.4': -87,
  'resource.heir.5': -84,
  'resource.heir.6': -82,
  'resource.heir.7': -81,
  'resource.heir.8': -81,
  'resource.alchemy.1': -57,
  'resource.alchemy.2': -52,
  'resource.alchemy.3': -47,
  'resource.brainwash.1': 20,
  'resource.brainwash.2': 20,
  'resource.brainwash.3': 20,
  'resource.brainwash.4': 16,
  'resource.brainwash.5': 16,
  'resource.brainwash.6': 16,
  'resource.brainwash.7': 16,
  'resource.wall.1': -8,
  'resource.wall.2': -6,
  'resource.wall.3': -6,
  'resource.march.1': 55,
  'resource.snipe.1': -35,
  'resource.snipe.2': -36,
};

/**
 * 능력별 보정값 (공통 가중치에 더한다, 0인 항목은 생략).
 * 그 능력을 가진 진영의 평가에만 쓰인다. tools/tune.ts가 대국 기록으로 학습한다.
 */
export const ABILITY_WEIGHTS: Readonly<Record<string, Readonly<Record<string, number>>>> = {
  telekinesis: {
    resourceFull: -0.15,
    resourceUsable: 0.34,
  },
  haste: {
    cooldownLeft: 0.58,
    resourceFull: -0.52,
    resourceUsable: -0.52,
  },
  teleport: {
    cooldownLeft: 0.44,
    resourceFull: -0.56,
    resourceUsable: 0.56,
  },
  revive: {
    cooldownLeft: -0.16,
    resourceFull: -0.24,
    resourceUsable: 0.31,
  },
  rewind: {
    cooldownLeft: -0.58,
    resourceFull: 0.21,
    resourceUsable: 0.37,
  },
  heavyInfantry: {
    resourceFull: 0.05,
    resourceUsable: 0.05,
  },
  lancer: {
    resourceFull: -0.51,
    resourceUsable: -0.51,
  },
  chariot: {
    resourceUsable: 0.37,
  },
  paladin: {
    resourceFull: -0.02,
    resourceUsable: 0.08,
  },
  empress: {
    resourceFull: 0.26,
    resourceUsable: 0.02,
  },
  heir: {
    resourceFull: 0.57,
    resourceUsable: -1.67,
  },
  alchemy: {
    resourceFull: 0.56,
    resourceUsable: -0.37,
  },
  brainwash: {
    resourceFull: -0.45,
    resourceUsable: 0.07,
  },
  wall: {
    cooldownLeft: -0.57,
    resourceFull: 0.03,
    resourceUsable: -0.08,
  },
  march: {
    resourceFull: 0.4,
    resourceUsable: 0.4,
  },
  snipe: {
    resourceFull: 0.26,
    resourceUsable: -0.09,
  },
};
