/**
 * 평가 가중치 (센티폰 단위, 폰 = 100 고정).
 * 부호가 있는 값이다: 음수는 감점 항목.
 * tools/tune.ts(Texel 튜닝)의 --apply가 이 파일을 다시 쓴다.
 * 마지막 튜닝: reports/tune-candidate.md
 */
export const WEIGHTS: Readonly<Record<string, number>> = {
  'piece.p': 100,
  'piece.n': 346,
  'piece.b': 346,
  'piece.r': 564,
  'piece.q': 1188,
  promotedKing: 355,
  'enhanced.p': 321,
  'enhanced.n': 494,
  'enhanced.b': 220,
  'enhanced.r': 91,
  pawnAdvance: 20,
  pawnCenter: 15,
  knightCenter: 42,
  bishopCenter: 33,
  queenCenter: 21,
  royalKingCenter: 3,
  rookOpenFile: 82,
  passedPawn: -57,
  passedPawnAdvance: 39,
  doubledPawn: -45,
  bishopPair: 53,
  // 손으로 고정한다 (FIXED_KEYS). 학습에 맡기면 883 이 붙고 계승자가 0% 가 된다
  extraRoyal: 0,
  // 손으로 고정한다 (FIXED_KEYS). 학습에 맡기면 295 가 붙고 여제가 29% 가 된다
  empressActive: 0,
  inCheck: -51,
  cooldown: -5,
  cooldownLeft: -5,
  resourceFull: 10,
  resourceUsable: -18,
  'resource.telekinesis.1': 80,
  'resource.telekinesis.2': 68,
  'resource.telekinesis.3': 63,
  'resource.haste.1': 201,
  'resource.haste.2': 190,
  'resource.haste.3': 186,
  'resource.teleport.1': 134,
  'resource.teleport.2': 113,
  'resource.revive.1': 43,
  'resource.revive.2': 48,
  'resource.revive.3': 50,
  'resource.revive.4': 50,
  'resource.revive.5': 48,
  'resource.revive.6': 47,
  'resource.revive.7': 46,
  'resource.rewind.1': 41,
  'resource.rewind.2': 41,
  'resource.rewind.3': 47,
  'resource.heavyInfantry.1': 97,
  'resource.lancer.1': -4,
  'resource.lancer.2': -15,
  'resource.chariot.1': -7,
  'resource.chariot.2': -10,
  'resource.paladin.1': 35,
  'resource.paladin.2': 35,
  'resource.empress.1': -11,
  'resource.empress.2': -7,
  'resource.heir.1': -115,
  'resource.heir.2': -107,
  'resource.heir.3': -90,
  'resource.heir.4': -80,
  'resource.heir.5': -75,
  'resource.heir.6': -73,
  'resource.heir.7': -72,
  'resource.heir.8': -72,
  'resource.alchemy.1': -59,
  'resource.alchemy.2': -47,
  'resource.alchemy.3': -39,
  'resource.brainwash.1': 23,
  'resource.brainwash.2': 24,
  'resource.brainwash.3': 22,
  'resource.brainwash.4': 16,
  'resource.brainwash.5': 15,
  'resource.brainwash.6': 13,
  'resource.brainwash.7': 13,
  'resource.wall.1': -7,
  'resource.wall.2': -4,
  'resource.wall.3': -5,
  'resource.march.1': 58,
  'resource.snipe.1': -33,
  'resource.snipe.2': -36,
  'revive.best': 6,
  'revive.pending': 2,
  'brainwash.best': 1,
  'brainwash.targets': 0,
  'telekinesis.target': 1,
  'teleport.swap': 10,
};

/**
 * 능력별 보정값 (공통 가중치에 더한다, 0인 항목은 생략).
 * 그 능력을 가진 진영의 평가에만 쓰인다. tools/tune.ts가 대국 기록으로 학습한다.
 */
export const ABILITY_WEIGHTS: Readonly<Record<string, Readonly<Record<string, number>>>> = {
  telekinesis: {
    resourceFull: -0.51,
    resourceUsable: 0.7,
  },
  haste: {
    cooldownLeft: 0.29,
    resourceFull: -0.23,
    resourceUsable: -0.23,
  },
  teleport: {
    cooldownLeft: 0.04,
    resourceFull: -0.44,
    resourceUsable: -0.58,
  },
  revive: {
    cooldownLeft: 0.14,
    resourceFull: 0.04,
    resourceUsable: 0.02,
  },
  rewind: {
    cooldownLeft: -0.19,
    resourceFull: -0.14,
    resourceUsable: 0.19,
  },
  heavyInfantry: {
    resourceFull: 0.43,
    resourceUsable: 0.43,
  },
  lancer: {
    resourceFull: -0.14,
    resourceUsable: -0.14,
  },
  chariot: {
    resourceFull: -0.26,
    resourceUsable: 0.15,
  },
  paladin: {
    resourceFull: 0.36,
    resourceUsable: -0.16,
  },
  empress: {
    resourceFull: -0.05,
    resourceUsable: -0.26,
  },
  heir: {
    resourceFull: 0.77,
    resourceUsable: -1.19,
  },
  alchemy: {
    resourceFull: 0.85,
    resourceUsable: 0.01,
  },
  brainwash: {
    resourceFull: -0.14,
    resourceUsable: 0.51,
  },
  wall: {
    cooldownLeft: -0.26,
    resourceFull: 0.4,
    resourceUsable: -0.33,
  },
  march: {
    resourceFull: 0.13,
    resourceUsable: 0.13,
  },
  snipe: {
    resourceFull: -0.01,
    resourceUsable: 0.26,
  },
};
